### ISSUE TITLE
Allow raw JSON string to be assigned as TemplateModel on TemplatedPostmarkMessage

### ISSUE THREAD

**Issue by atheken** [ActiveCampaign/postmark-dotnet#28]
A customer has requested that we allow them to assign a raw String as the Template Model for a TemplatedPostmarkMessage. 

Let's use this issue to discuss that feature and whether we can support it.

**Comment by sergeydgr8** [comment]
+1 for this. The documentation does not explain how to use the TemplateModel, and thus it's ambiguous and confusing to send data to Postmark to send templated emails.

**Comment by atheken** [comment]
Perhaps the real issue is that the `TemplateModel` property documentation just needs to describe better what it will work? The reason the property allows `object` is because we want to allow you to assign POCOs, and Anonymous types to it, rather than forcing a conversion to `IDictionary<string, object>`, the downside of this is that this can include some other types in the C# type system that don't make sense. (Specifically, scalars like: `string`, `int`, `float`, and `arrays`.). 

So maybe including that in the docs will resolve the ambiguity?

**Comment by stuartbale** [comment]
So the reason why I originally requested this is because I store the template model as a JSON string in a database table. So, currently:
1. I read the string from the table;
2. deserialize it to a POCO;
3. set the TemplatedPostmarkMessage.TemplateModel property;
4. where it is serialized back to a JSON string; and
5. sent on to the Postmark service.

So assigning the JSON string directly would mean steps #2 & #4 wouldn't be needed.

Having said all that, I have implemented my own direct https call to the web api, but I would certainly prefer to use the Postmark library.
